name: Go setup
description: "Sets up the Go environment"

inputs:
  project-name:
    description: "name of the project (should match directory)"
    required: true

outputs:
  cache-key:
    description: "Contains key of the cache"
    value: ${{ steps.go-mod-cache.outputs.cache-primary-key }}
  is-cache-hit:
    description: '"true" if the cache got hit for go.mod'
    value: ${{ steps.go-mod-cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - id: go-cache-path
      shell: sh
      run: |
        echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

    - run: git config --global --add safe.directory /__w/melvin.la/melvin.la
      shell: sh

    - name: Restore & Update Go cache
      id: go-mod-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.go-cache-path.outputs.go-mod }}
        key: ${{ runner.os }}-${{ inputs.project-name }}-go-mod-${{ hashFiles(format('./{0}/go.sum',inputs.project-name)) }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.project-name }}-go-mod-
