//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BlogPostRevs = newBlogPostRevsTable("public", "blog_post_revs", "")

type blogPostRevsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	BlogPostID   postgres.ColumnString
	Title        postgres.ColumnString
	Slug         postgres.ColumnString
	ThumbnailURL postgres.ColumnString
	Description  postgres.ColumnString
	ContentJSON  postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	DeletedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type BlogPostRevsTable struct {
	blogPostRevsTable

	EXCLUDED blogPostRevsTable
}

// AS creates new BlogPostRevsTable with assigned alias
func (a BlogPostRevsTable) AS(alias string) *BlogPostRevsTable {
	return newBlogPostRevsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BlogPostRevsTable with assigned schema name
func (a BlogPostRevsTable) FromSchema(schemaName string) *BlogPostRevsTable {
	return newBlogPostRevsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BlogPostRevsTable with assigned table prefix
func (a BlogPostRevsTable) WithPrefix(prefix string) *BlogPostRevsTable {
	return newBlogPostRevsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BlogPostRevsTable with assigned table suffix
func (a BlogPostRevsTable) WithSuffix(suffix string) *BlogPostRevsTable {
	return newBlogPostRevsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBlogPostRevsTable(schemaName, tableName, alias string) *BlogPostRevsTable {
	return &BlogPostRevsTable{
		blogPostRevsTable: newBlogPostRevsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newBlogPostRevsTableImpl("", "excluded", ""),
	}
}

func newBlogPostRevsTableImpl(schemaName, tableName, alias string) blogPostRevsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		BlogPostIDColumn   = postgres.StringColumn("blog_post_id")
		TitleColumn        = postgres.StringColumn("title")
		SlugColumn         = postgres.StringColumn("slug")
		ThumbnailURLColumn = postgres.StringColumn("thumbnail_url")
		DescriptionColumn  = postgres.StringColumn("description")
		ContentJSONColumn  = postgres.StringColumn("content_json")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		DeletedAtColumn    = postgres.TimestampzColumn("deleted_at")
		allColumns         = postgres.ColumnList{IDColumn, BlogPostIDColumn, TitleColumn, SlugColumn, ThumbnailURLColumn, DescriptionColumn, ContentJSONColumn, CreatedAtColumn, DeletedAtColumn}
		mutableColumns     = postgres.ColumnList{BlogPostIDColumn, TitleColumn, SlugColumn, ThumbnailURLColumn, DescriptionColumn, ContentJSONColumn, CreatedAtColumn, DeletedAtColumn}
	)

	return blogPostRevsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		BlogPostID:   BlogPostIDColumn,
		Title:        TitleColumn,
		Slug:         SlugColumn,
		ThumbnailURL: ThumbnailURLColumn,
		Description:  DescriptionColumn,
		ContentJSON:  ContentJSONColumn,
		CreatedAt:    CreatedAtColumn,
		DeletedAt:    DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
