//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BlogPosts = newBlogPostsTable("public", "blog_posts", "")

type blogPostsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	Title        postgres.ColumnString
	Slug         postgres.ColumnString
	ThumbnailURL postgres.ColumnString
	Description  postgres.ColumnString
	ContentJSON  postgres.ColumnString
	PublishedAt  postgres.ColumnTimestampz
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz
	DeletedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type BlogPostsTable struct {
	blogPostsTable

	EXCLUDED blogPostsTable
}

// AS creates new BlogPostsTable with assigned alias
func (a BlogPostsTable) AS(alias string) *BlogPostsTable {
	return newBlogPostsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BlogPostsTable with assigned schema name
func (a BlogPostsTable) FromSchema(schemaName string) *BlogPostsTable {
	return newBlogPostsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BlogPostsTable with assigned table prefix
func (a BlogPostsTable) WithPrefix(prefix string) *BlogPostsTable {
	return newBlogPostsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BlogPostsTable with assigned table suffix
func (a BlogPostsTable) WithSuffix(suffix string) *BlogPostsTable {
	return newBlogPostsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBlogPostsTable(schemaName, tableName, alias string) *BlogPostsTable {
	return &BlogPostsTable{
		blogPostsTable: newBlogPostsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newBlogPostsTableImpl("", "excluded", ""),
	}
}

func newBlogPostsTableImpl(schemaName, tableName, alias string) blogPostsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		TitleColumn        = postgres.StringColumn("title")
		SlugColumn         = postgres.StringColumn("slug")
		ThumbnailURLColumn = postgres.StringColumn("thumbnail_url")
		DescriptionColumn  = postgres.StringColumn("description")
		ContentJSONColumn  = postgres.StringColumn("content_json")
		PublishedAtColumn  = postgres.TimestampzColumn("published_at")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn    = postgres.TimestampzColumn("deleted_at")
		allColumns         = postgres.ColumnList{IDColumn, TitleColumn, SlugColumn, ThumbnailURLColumn, DescriptionColumn, ContentJSONColumn, PublishedAtColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns     = postgres.ColumnList{TitleColumn, SlugColumn, ThumbnailURLColumn, DescriptionColumn, ContentJSONColumn, PublishedAtColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
	)

	return blogPostsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Title:        TitleColumn,
		Slug:         SlugColumn,
		ThumbnailURL: ThumbnailURLColumn,
		Description:  DescriptionColumn,
		ContentJSON:  ContentJSONColumn,
		PublishedAt:  PublishedAtColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		DeletedAt:    DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
