//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserSessions = newUserSessionsTable("public", "user_sessions", "")

type userSessionsTable struct {
	postgres.Table

	// Columns
	Token        postgres.ColumnString
	UserID       postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz
	DeletedAt    postgres.ColumnTimestampz
	RefreshToken postgres.ColumnString
	ExpiresAt    postgres.ColumnTimestampz
	RefreshedAs  postgres.ColumnString
	IPAddress    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserSessionsTable struct {
	userSessionsTable

	EXCLUDED userSessionsTable
}

// AS creates new UserSessionsTable with assigned alias
func (a UserSessionsTable) AS(alias string) *UserSessionsTable {
	return newUserSessionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserSessionsTable with assigned schema name
func (a UserSessionsTable) FromSchema(schemaName string) *UserSessionsTable {
	return newUserSessionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserSessionsTable with assigned table prefix
func (a UserSessionsTable) WithPrefix(prefix string) *UserSessionsTable {
	return newUserSessionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserSessionsTable with assigned table suffix
func (a UserSessionsTable) WithSuffix(suffix string) *UserSessionsTable {
	return newUserSessionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserSessionsTable(schemaName, tableName, alias string) *UserSessionsTable {
	return &UserSessionsTable{
		userSessionsTable: newUserSessionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newUserSessionsTableImpl("", "excluded", ""),
	}
}

func newUserSessionsTableImpl(schemaName, tableName, alias string) userSessionsTable {
	var (
		TokenColumn        = postgres.StringColumn("token")
		UserIDColumn       = postgres.StringColumn("user_id")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn    = postgres.TimestampzColumn("deleted_at")
		RefreshTokenColumn = postgres.StringColumn("refresh_token")
		ExpiresAtColumn    = postgres.TimestampzColumn("expires_at")
		RefreshedAsColumn  = postgres.StringColumn("refreshed_as")
		IPAddressColumn    = postgres.StringColumn("ip_address")
		allColumns         = postgres.ColumnList{TokenColumn, UserIDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, RefreshTokenColumn, ExpiresAtColumn, RefreshedAsColumn, IPAddressColumn}
		mutableColumns     = postgres.ColumnList{UserIDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, RefreshTokenColumn, ExpiresAtColumn, RefreshedAsColumn, IPAddressColumn}
	)

	return userSessionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Token:        TokenColumn,
		UserID:       UserIDColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		DeletedAt:    DeletedAtColumn,
		RefreshToken: RefreshTokenColumn,
		ExpiresAt:    ExpiresAtColumn,
		RefreshedAs:  RefreshedAsColumn,
		IPAddress:    IPAddressColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
