//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type BlogPosts struct {
	ID           uuid.UUID `sql:"primary_key"`
	Title        string
	Slug         string
	ThumbnailURL *string
	Description  *string
	ContentJSON  *string
	PublishedAt  *time.Time
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	DeletedAt    *time.Time
}
