//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserSessions struct {
	Token        uuid.UUID `sql:"primary_key"`
	UserID       uuid.UUID
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	DeletedAt    *time.Time
	RefreshToken uuid.UUID
	ExpiresAt    time.Time
	RefreshedAs  *uuid.UUID
	IPAddress    *string
}
