name: Node setup
description: "Sets up the environment for jobs using node"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        package_json_file: "web/package.json"

    - uses: actions/setup-node@v6
      with:
        node-version-file: "web/.nvmrc"
        cache: "pnpm"
        cache-dependency-path: web/pnpm-lock.yaml

    - name: Restore Next.js cache
      uses: actions/cache@v5
      with:
        path: |
          ${{ github.workspace }}/web/.next/cache
        key: ${{ runner.os }}-web-nextjs-${{ hashFiles('./web/pnpm-lock.yaml') }}-${{ hashFiles('./web/**/*.js', './web/**/*.jsx', './web/**/*.ts', './web/**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-web-nextjs-${{ hashFiles('./web/pnpm-lock.yaml') }}-
          ${{ runner.os }}-web-nextjs-

    - name: install deps
      shell: bash
      run: cd web && pnpm install --frozen-lockfile
