name: Node setup
description: "Sets up the environment for jobs using node"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v6.0.4
      with:
        package_json_file: "package.json"

    - uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
        cache-dependency-path: pnpm-lock.yaml

    - name: Restore Turbo cache
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/.turbo
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: install deps
      shell: bash
      run: pnpm install --frozen-lockfile
