name: Node setup
description: "Sets up the environment for jobs using node"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        package_json_file: "web/apps/front/package.json"

    - uses: actions/setup-node@v5
      with:
        node-version-file: "web/apps/front/.nvmrc"
        cache: "pnpm"
        cache-dependency-path: web/apps/front/pnpm-lock.yaml

    - name: Restore Next.js cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/web/apps/front/.next/cache
        key: ${{ runner.os }}-web-apps-front-nextjs-${{ hashFiles('./web/apps/front/pnpm-lock.yaml') }}-${{ hashFiles('./web/apps/front/**/*.js', './web/apps/front/**/*.jsx', './web/apps/front/**/*.ts', './web/apps/front/**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-web-apps-front-nextjs-${{ hashFiles('./web/apps/front/pnpm-lock.yaml') }}-
          ${{ runner.os }}-web-apps-front-nextjs-

    - name: install deps
      shell: bash
      run: cd web/apps/front && pnpm install --frozen-lockfile
