import type { BeatmakerState, TrackId } from "./types";
import { buildTrackRecord } from "./types";

type PresetDef = Omit<BeatmakerState, "isPlaying">;

const makeTrack = (steps: boolean[]): BeatmakerState["tracks"][TrackId] => ({
  muted: false,
  pan: 0,
  steps,
  volume: 0.8,
});

const blank = (n: number) => Array.from<boolean>({ length: n }).fill(false);

const makeBlankTracks = (stepCount: BeatmakerState["stepCount"]): BeatmakerState["tracks"] =>
  buildTrackRecord(() => makeTrack(blank(stepCount)));

// 16-step helpers: ON=true, OFF=false
const OFF = false,
  ON = true;

const BASIC_ROCK: PresetDef = {
  bpm: 120,
  kit: "808",
  stepCount: 16,
  tracks: {
    clap: makeTrack(blank(16)),
    hihat: makeTrack([ON, OFF, ON, OFF, ON, OFF, ON, OFF, ON, OFF, ON, OFF, ON, OFF, ON, OFF]),
    kick: makeTrack([ON, OFF, OFF, OFF, OFF, OFF, OFF, OFF, ON, OFF, OFF, OFF, OFF, OFF, OFF, OFF]),
    openhat: makeTrack(blank(16)),
    ride: makeTrack(blank(16)),
    snare: makeTrack([
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
    ]),
  },
};

const FOUR_ON_FLOOR: PresetDef = {
  bpm: 128,
  kit: "808",
  stepCount: 16,
  tracks: {
    clap: makeTrack(blank(16)),
    hihat: makeTrack([
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
    ]),
    kick: makeTrack([ON, OFF, OFF, OFF, ON, OFF, OFF, OFF, ON, OFF, OFF, OFF, ON, OFF, OFF, OFF]),
    openhat: makeTrack([
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
    ]),
    ride: makeTrack(blank(16)),
    snare: makeTrack(blank(16)),
  },
};

const BOOM_BAP: PresetDef = {
  bpm: 90,
  kit: "808",
  stepCount: 16,
  tracks: {
    clap: makeTrack([OFF, OFF, OFF, OFF, ON, OFF, OFF, OFF, OFF, OFF, OFF, OFF, ON, OFF, OFF, OFF]),
    hihat: makeTrack([ON, OFF, ON, OFF, ON, OFF, ON, OFF, ON, OFF, ON, ON, ON, OFF, ON, OFF]),
    kick: makeTrack([ON, OFF, OFF, OFF, OFF, OFF, OFF, ON, OFF, OFF, OFF, OFF, ON, OFF, OFF, OFF]),
    openhat: makeTrack(blank(16)),
    ride: makeTrack(blank(16)),
    snare: makeTrack([
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
    ]),
  },
};

// 32-step trap pattern (semiquavers)
const TRAP: PresetDef = {
  bpm: 140,
  kit: "808",
  stepCount: 32,
  tracks: {
    clap: makeTrack([
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
    ]),
    hihat: makeTrack(Array.from({ length: 32 }, (_, i) => i % 2 === 0)),
    kick: makeTrack([
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
    ]),
    openhat: makeTrack(blank(32)),
    ride: makeTrack(blank(32)),
    snare: makeTrack([
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      ON,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
      OFF,
    ]),
  },
};

const BLANK_16: PresetDef = {
  bpm: 120,
  kit: "808",
  stepCount: 16,
  tracks: makeBlankTracks(16),
};

export const PRESETS: Record<string, PresetDef> = {
  "basic-rock": BASIC_ROCK,
  blank: BLANK_16,
  "boom-bap": BOOM_BAP,
  "four-on-floor": FOUR_ON_FLOOR,
  trap: TRAP,
};

export const buildDefaultState = (): BeatmakerState => ({
  ...PRESETS["basic-rock"],
  isPlaying: false,
});
