version: "3"

dotenv: [".env", ".env.local", ".env.development"]

includes:
  ci: ./Taskfile_CI.yml

vars:
  BIN_OUT: "./bin/api"

tasks:
  install-deps:
    cmds:
      - go install github.com/daveshanley/vacuumv0.23.2
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@1401fbe26ce7e128e9963786742490ff444e3795

  build:
    cmds:
      - CGO_ENABLED=0 go build -v -o {{.BIN_OUT}} github.com/Nivl/melvin.la/api/cmd/api
    generates:
      - "{{.BIN_OUT}}"

  start:
    deps: [build]
    cmds:
      - "{{.BIN_OUT}}"

  dev:
    deps: [build]
    cmds:
      - "{{.BIN_OUT}}"
    sources:
      - ./**/*.go
      - ./**/*.env
      - ./**/*.mod
      - ./**/*.sum
    generates:
      - "{{.BIN_OUT}}"

  lint:
    cmds:
      - golangci-lint run ./...

  generate:
    cmds:
      - go generate ./...
      - go mod tidy

  deps-upgrade:
    cmds:
      - go get -t -u ./...
      - go mod tidy

  tidy:
    cmds:
      - go mod tidy
      - go generate ./...

  test: go test -race ./...
