version: "3"

dotenv: [".env", ".env.local", ".env.development"]

includes:
  ci: ./Taskfile_CI.yml

vars:
  BIN_OUT: "./bin/api"

tasks:
  build:
    cmds:
      - CGO_ENABLED=0 go build -v -o {{.BIN_OUT}} github.com/Nivl/melvin.la/api/cmd/api
    generates:
      - "{{.BIN_OUT}}"

  start:
    deps: [build]
    cmds:
      - "{{.BIN_OUT}}"

  dev:
    deps: [build]
    cmds:
      - "{{.BIN_OUT}}"
    sources:
      - ./**/*.go
      - ./**/*.env
      - ./**/*.mod
      - ./**/*.sum
    generates:
      - "{{.BIN_OUT}}"

  lint:
    cmds:
      - golangci-lint run ./...

  generate:
    cmds:
      - go generate ./...
      - go mod tidy

  deps-upgrade:
    cmds:
      - go get -t -u ./...
      - go mod tidy

  tidy:
    cmds:
      - go mod tidy
      - go tool github.com/daveshanley/vacuum bundle -q -p openapi/ openapi/openapi.yml internal/gen/openapi.yml
      - go generate ./...

  test: go test -race ./...
