name: images

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Don't run more than one workflow for the same branch at a time
# This is to save credits on the CI provider
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-go-service-image-dev

jobs:
  perpare-env:
    name: detect what files changed
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nivl/melvin.la-go-service-image-dev:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    outputs:
      go-service-image-dev: ${{ steps.changes.outputs.go-service-image-dev }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/melvin.la/melvin.la

      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            go-service-image-dev:
              - 'docker/go-service-image-dev/**'
              - '.github/workflows/go-service-image-dev.yml'

  go-service-image-dev:
    if: ${{ needs.perpare-env.outputs.go-service-image-dev == 'true' }}
    needs: perpare-env
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/go-service-image-dev
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # This job is what github action will check to see if a PR is ready to
  # be merged.
  images-required-check:
    needs:
      [
        perpare-env,
        go-service-image-dev,
      ]
    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
    if: always()
    runs-on: ubuntu-latest
    steps:
      # If any jobs we depend on fail, we will fail since this is a required check
      # NOTE: A timeout is considered a failure
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
