name: images

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  packages: write

# Don't run more than one workflow for the same branch at a time
# This is to save credits on the CI provider
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-go-service-image-dev

jobs:
  perpare-env:
    name: detect what files changed
    runs-on: ubuntu-latest
    outputs:
      go-service-image-dev: ${{ steps.changes.outputs.go-service-image-dev }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/melvin.la/melvin.la

      - name: Check for file changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            go-service-image-dev:
              - 'docker/go-service-image-dev/**'
              - '.github/workflows/images.yml'

  go-service-image-dev:
    if: ${{ needs.perpare-env.outputs.go-service-image-dev == 'true' }}
    needs: perpare-env
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required to publish or update container images in the GitHub Container Registry.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@3d100841f68d4548bf57e52eb27bd33ec5069f55
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@be19121bfd18b9c1ac415d9571d4f67b9b357886
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=sha,prefix=sha-,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./docker/go-service-image-dev
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # This job is what github action will check to see if a PR is ready to
  # be merged.
  images-required-check:
    needs:
      [
        perpare-env,
        go-service-image-dev,
      ]
    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
    if: always()
    runs-on: ubuntu-latest
    steps:
      # If any jobs we depend on fail, we will fail since this is a required check
      # NOTE: A timeout is considered a failure
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
