name: renovate

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/renovate.yml'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/renovate.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npx --yes --package renovate -- renovate-config-validator --strict .github/renovate.json
