name: tooling

on:
  [push, pull_request]

# Don't run more than one workflow for the same branch at a time
# This is to save credits on the CI provider
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  perpare-env:
    name: detect what files changed
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nivl/melvin.la-go-service-image-dev:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    outputs:
      renovate: ${{ steps.changes.outputs.renovate }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/melvin.la/melvin.la

      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            renovate:
              - '.github/workflows/renovate.yml'

  renovate-lint:
    if: ${{ needs.perpare-env.outputs.renovate == 'true' }}
    needs: perpare-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npx --yes --package renovate -- renovate-config-validator --strict .github/renovate.json

  # This job is what github action will check to see if a PR is ready to
  # be merged.
  tooling-required-check:
    needs:
      [
        perpare-env,
        renovate-lint,
      ]
    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
    if: always()
    runs-on: ubuntu-latest
    steps:
      # If any jobs we depend on fail, we will fail since this is a required check
      # NOTE: A timeout is considered a failure
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
