name: tooling

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

# Don't run more than one workflow for the same branch at a time
# This is to save credits on the CI provider
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-env:
    name: detect what files changed
    runs-on: ubuntu-latest
    outputs:
      renovate: ${{ steps.changes.outputs.renovate }}
    steps:
      - uses: actions/checkout@v5
      - run: git config --global --add safe.directory /__w/melvin.la/melvin.la

      - name: Check for file changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            renovate:
              - '.github/renovate.json'

  renovate-lint:
    if: ${{ needs.prepare-env.outputs.renovate == 'true' }}
    needs: prepare-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
    - run: npx --yes --package renovate -- renovate-config-validator --strict .github/renovate.json

  # This job is what github action will check to see if a PR is ready to
  # be merged.
  tooling-required-check:
    needs:
      [
        prepare-env,
        renovate-lint,
      ]
    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
    if: always()
    runs-on: ubuntu-latest
    steps:
      # If any jobs we depend on fail, we will fail since this is a required check
      # NOTE: A timeout is considered a failure
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
