ignoredBuiltDependencies:
  - canvas
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

# Deps allowed to run scripts during installation
# This is unsecure, so we limit it to only these packages that we trust
onlyBuiltDependencies:
  - "@heroui/shared-utils" # May be gone in heroui v3
  - msw # https://github.com/mswjs/msw/issues/1297

minimumReleaseAge: 20160
minimumReleaseAgeExclude:
  # Remove Feb 16th 2026
  - "jsdom@28.0.0"
  - "whatwg-url@16.0.0"
  # Remove Feb 17th 2026
  - "@sentry/bundler-plugin-core@4.9.0"
  - "@sentry/webpack-plugin@4.9.0"
  - "@sentry/babel-plugin-component-annotate@4.9.0"
  - "icu-minify@4.8.2"
  - "next-intl-swc-plugin-extractor@4.8.2"
  - "use-intl@4.8.2"
  - "framer-motion@12.30.0"
  - "motion-dom@12.30.0"
  - "data-urls@7.0.0"
  # Remove Feb 18th 2026
  - "next-mdx-remote@6.0.0"
