ignoredBuiltDependencies:
  - canvas
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

# Deps allowed to run scripts during installation
# This is unsecure, so we limit it to only these packages that we trust
onlyBuiltDependencies:
  - "@heroui/shared-utils" # May be gone in heroui v3
  - msw # https://github.com/mswjs/msw/issues/1297

minimumReleaseAge: 20160

minimumReleaseAgeExclude:
  # temporary because we're replacing it with oxc
  - "typescript-eslint@8.58.1"
  - "@typescript-eslint/utils@8.58.1"
  - "@typescript-eslint/types@8.58.1"
  - "@typescript-eslint/scope-manager@8.58.1"
  - "@typescript-eslint/parser@8.58.1"
  - "@typescript-eslint/typescript-estree@8.58.1"
  - "@typescript-eslint/visitor-keys@8.58.1"
  - "@typescript-eslint/eslint-plugin@8.58.1"
  - "@typescript-eslint/tsconfig-utils@8.58.1"
  - "@typescript-eslint/project-service@8.58.1"
  - "@typescript-eslint/type-utils@8.58.1"
