ignoredBuiltDependencies:
  - canvas
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

# Deps allowed to run scripts during installation
# This is unsecure, so we limit it to only these packages that we trust
onlyBuiltDependencies:
  - "@heroui/shared-utils" # May be gone in heroui v3
  - msw # https://github.com/mswjs/msw/issues/1297

minimumReleaseAge: 20160
minimumReleaseAgeExclude:
  # Remove Feb 4th 2026
  - "prettier@3.8.1"
  - "@opentelemetry/context-async-hooks@2.5.0"
  - "@opentelemetry/resources@2.5.0"
  - "@opentelemetry/instrumentation@0.211.0"
  - "@opentelemetry/sdk-trace-base@2.5.0"
  - "@opentelemetry/core@2.5.0"
  # Remove Feb 5th 2026
  - "@opentelemetry/api-logs@0.211.0"
  - "vitest@4.0.18"
  - "@vitest/spy@4.0.18"
  - "@vitest/mocker@4.0.18"
  - "@vitest/runner@4.0.18"
  - "@vitest/utils@4.0.18"
  - "@vitest/expect@4.0.18"
  - "@vitest/pretty-format@4.0.18"
  - "@vitest/snapshot@4.0.18"
  - "@opentelemetry/instrumentation-amqplib@0.58.0"
  - "@opentelemetry/instrumentation-dataloader@0.28.0"
  - "@opentelemetry/instrumentation-connect@0.54.0"
  - "@opentelemetry/instrumentation-kafkajs@0.20.0"
  - "@opentelemetry/instrumentation-fs@0.30.0"
  - "@opentelemetry/instrumentation-express@0.59.0"
  - "@opentelemetry/instrumentation-fastify@0.46.0"
  - "@opentelemetry/instrumentation-graphql@0.58.0"
  - "@opentelemetry/instrumentation-hapi@0.57.0"
  - "@opentelemetry/instrumentation-http@0.211.0"
  - "@opentelemetry/instrumentation-ioredis@0.59.0"
  - "@opentelemetry/instrumentation-koa@0.59.0"
  - "@opentelemetry/instrumentation-mongodb@0.64.0"
  - "@opentelemetry/instrumentation-mysql@0.57.0"
  - "@opentelemetry/instrumentation-mysql2@0.57.0"
  - "@opentelemetry/instrumentation-nestjs-core@0.46.0"
  - "@opentelemetry/instrumentation-pg@0.63.0"
  - "@opentelemetry/instrumentation-redis-4@0.46.0"
  - "@opentelemetry/instrumentation-generic-pool@0.54.0"
  - "@opentelemetry/instrumentation-lru-memoizer@0.55.0"
  - "@opentelemetry/instrumentation-memcached@0.44.0"
  - "@opentelemetry/instrumentation-redis@0.59.0"
  - "@opentelemetry/instrumentation-restify@0.48.0"
  - "@opentelemetry/instrumentation-router@0.46.0"
  - "@opentelemetry/instrumentation-tedious@0.30.0"
  - "@opentelemetry/instrumentation-undici@0.21.0"
  - "@opentelemetry/instrumentation-mongoose@0.57.0"
  - "@opentelemetry/instrumentation-knex@0.55.0"
  - "@opentelemetry/instrumentation-aws-sdk@0.56.0"
  - "@opentelemetry/instrumentation-aws-lambda@0.56.0"
  - "@opentelemetry/instrumentation-bunyan@0.43.0"
  - "@opentelemetry/instrumentation-cucumber@0.14.0"
  - "@opentelemetry/instrumentation-dns@0.43.0"
  - "@opentelemetry/instrumentation-pino@0.53.0"
  - "@opentelemetry/instrumentation-winston@0.46.0"
  # Remove Feb 6th 2026
  - "@tanstack/react-query@5.90.20"
  - "@tanstack/query-core@5.90.20"
  - "@playwright/test@1.58.0"
  - "playwright@1.58.0"
  - "playwright-core@1.58.0"
  - "lucide-react@0.563.0"
  # Remove Feb 9th 2026
  - "eslint-plugin-playwright@2.5.1"
  - "typescript-eslint@8.54.0"
  - "@typescript-eslint/utils@8.54.0"
  - "@typescript-eslint/eslint-plugin@8.54.0"
  - "@typescript-eslint/parser@8.54.0"
  - "@typescript-eslint/typescript-estree@8.54.0"
  - "@typescript-eslint/tsconfig-utils@8.54.0"
  - "@typescript-eslint/project-service@8.54.0"
  - "@typescript-eslint/type-utils@8.54.0"
  - "@typescript-eslint/types@8.54.0"
  - "@typescript-eslint/scope-manager@8.54.0"
  - "@typescript-eslint/visitor-keys@8.54.0"
  - "motion@12.29.2"
  - "motion-utils@12.29.2"
  - "react@19.2.4"
  - "react-dom@19.2.4"
  # Remove Feb 10th 2026
  - "@types/react@19.2.10"
  - "@next/swc-darwin-x64@16.1.6"
  - "@next/swc-win32-arm64-msvc@16.1.6"
  - "@next/swc-linux-x64-musl@16.1.6"
  - "@next/env@16.1.6"
  - "@next/swc-linux-arm64-gnu@16.1.6"
  - "@next/swc-darwin-arm64@16.1.6"
  - "@next/swc-linux-arm64-musl@16.1.6"
  - "@next/swc-linux-x64-gnu@16.1.6"
  - "@next/swc-win32-x64-msvc@16.1.6"
  - "@storybook/core-webpack@10.2.1"
  - "import-in-the-middle@2.0.6"
  - "@storybook/addon-themes@10.2.1"
  - "@storybook/nextjs@10.2.1"
  - "@storybook/addon-links@10.2.1"
  - "@storybook/addon-docs@10.2.1"
  - "@storybook/csf-plugin@10.2.1"
  - "@storybook/react-dom-shim@10.2.1"
  - "@storybook/react@10.2.1"
  - "@storybook/preset-react-webpack@10.2.1"
  - "@storybook/builder-webpack5@10.2.1"
  - "eslint-plugin-storybook@10.2.1"
  - "storybook@10.2.1"
  - "@next/eslint-plugin-next@16.1.6"
  - "eslint-config-next@16.1.6"
  - "next@16.1.6"
  # Remove Feb 11th 2026
  - "next-intl@4.8.0"
  # Remove Feb 12th 2026
  - "@sentry/nextjs@10.38.0"
  - "@sentry-internal/browser-utils@10.38.0"
  - "@sentry/opentelemetry@10.38.0"
  - "@sentry/vercel-edge@10.38.0"
  - "@sentry/core@10.38.0"
  - "@sentry/react@10.38.0"
  - "@sentry/node@10.38.0"
  - "@sentry/node-core@10.38.0"
  - "@sentry/browser@10.38.0"
  - "@sentry-internal/replay@10.38.0"
  - "@sentry-internal/replay-canvas@10.38.0"
  - "@sentry-internal/feedback@10.38.0"
  # Remove Feb 15th 2026
  - "@babel/core@7.29.0"
  - "@babel/code-frame@7.29.0"
  - "@babel/types@7.29.0"
  - "@babel/generator@7.29.0"
  - "@babel/traverse@7.29.0"
  - "@babel/parser@7.29.0"
  # Remove Feb 14th 2026
  - "rollup@4.57.1"
  - "@rollup/rollup-linux-loong64-musl@4.57.1"
  - "@rollup/rollup-linux-ppc64-musl@4.57.1"
  - "@rollup/rollup-linux-loong64-gnu@4.57.1"
  - "@rollup/rollup-win32-x64-gnu@4.57.1"
  - "@rollup/rollup-linux-ppc64-gnu@4.57.1"
  - "@rollup/rollup-linux-riscv64-musl@4.57.1"
  - "@rollup/rollup-openbsd-x64@4.57.1"
  - "@rollup/rollup-freebsd-arm64@4.57.1"
  - "@rollup/rollup-freebsd-x64@4.57.1"
  - "@rollup/rollup-openharmony-arm64@4.57.1"
  - "@rollup/rollup-android-arm-eabi@4.57.1"
  - "@rollup/rollup-win32-arm64-msvc@4.57.1"
  - "@rollup/rollup-linux-arm-musleabihf@4.57.1"
  - "@rollup/rollup-linux-riscv64-gnu@4.57.1"
  - "@rollup/rollup-linux-s390x-gnu@4.57.1"
  - "@rollup/rollup-linux-arm64-musl@4.57.1"
  - "@rollup/rollup-win32-ia32-msvc@4.57.1"
  - "@rollup/rollup-linux-x64-gnu@4.57.1"
  - "@rollup/rollup-linux-x64-musl@4.57.1"
  - "@rollup/rollup-darwin-arm64@4.57.1"
  - "@rollup/rollup-android-arm64@4.57.1"
  - "@rollup/rollup-win32-x64-msvc@4.57.1"
  - "@rollup/rollup-linux-arm-gnueabihf@4.57.1"
  - "@rollup/rollup-darwin-x64@4.57.1"
  - "@rollup/rollup-linux-arm64-gnu@4.57.1"
  # Remove Feb 17th 2026
  - "@sentry/bundler-plugin-core@4.9.0"
  - "@sentry/webpack-plugin@4.9.0"
  - "@sentry/babel-plugin-component-annotate@4.9.0"
  - "icu-minify@4.8.2"
  - "next-intl-swc-plugin-extractor@4.8.2"
  - "use-intl@4.8.2"
  - "framer-motion@12.30.0"
  - "motion-dom@12.30.0"
