ignoredBuiltDependencies:
  - canvas
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

# Deps allowed to run scripts during installation
# This is unsecure, so we limit it to only these packages that we trust
onlyBuiltDependencies:
  - "@heroui/shared-utils" # May be gone in heroui v3
  - msw # https://github.com/mswjs/msw/issues/1297

minimumReleaseAge: 20160

minimumReleaseAgeExclude:
  - "@heroui/autocomplete"
  - "@heroui/avatar"
  - "@heroui/button"
  - "@heroui/card"
  - "@heroui/chip"
  - "@heroui/code"
  - "@heroui/date-input"
  - "@heroui/dropdown"
  - "@heroui/form"
  - "@heroui/input"
  - "@heroui/link"
  - "@heroui/modal"
  - "@heroui/navbar"
  - "@heroui/number-input"
  - "@heroui/progress"
  - "@heroui/react"
  - "@heroui/select"
  - "@heroui/skeleton"
  - "@heroui/slider"
  - "@heroui/switch"
  - "@heroui/system"
  - "@heroui/table"
  - "@heroui/theme"
  - "@heroui/toast"
  - "@heroui/tooltip"
  - "@heroui/shared-icons"
  - "@heroui/shared-utils"
  - "@heroui/react-mcp"
