packages:
  - apps/*
  - packages/*
catalogMode: strict
cleanupUnusedCatalogs: true
catalog:
  "@chromatic-com/storybook": 4.1.3
  "@eslint/eslintrc": 3.3.1
  "@eslint/js": 9.39.1
  "@heroui/autocomplete": 2.3.29
  "@heroui/avatar": 2.2.22
  "@heroui/button": 2.2.27
  "@heroui/card": 2.2.25
  "@heroui/chip": 2.2.22
  "@heroui/code": 2.2.21
  "@heroui/date-input": 2.3.27
  "@heroui/dropdown": 2.3.27
  "@heroui/form": 2.1.27
  "@heroui/input": 2.4.28
  "@heroui/link": 2.2.23
  "@heroui/modal": 2.2.24
  "@heroui/navbar": 2.2.25
  "@heroui/number-input": 2.0.18
  "@heroui/progress": 2.2.22
  "@heroui/react": 2.8.5
  "@heroui/select": 2.4.28
  "@heroui/skeleton": 2.2.17
  "@heroui/slider": 2.4.24
  "@heroui/switch": 2.2.24
  "@heroui/system": 2.4.23
  "@heroui/table": 2.2.27
  "@heroui/theme": 2.4.23
  "@heroui/tooltip": 2.2.24
  "@internationalized/date": 3.10.0
  "@next/eslint-plugin-next": 16.0.4
  "@radix-ui/react-toggle-group": 1.1.11
  "@storybook/addon-docs": 10.0.8
  "@storybook/addon-links": 10.0.8
  "@storybook/addon-themes": 10.0.8
  "@storybook/nextjs": 10.0.8
  "@tailwindcss/postcss": 4.1.17
  "@tanstack/react-query": 5.90.11
  "@testing-library/dom": 10.4.1
  "@testing-library/react": 16.3.0
  "@testing-library/user-event": 14.6.1
  "@types/google.maps": 3.58.1
  "@types/node": 24.10.1
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@types/react-syntax-highlighter": 15.5.13
  "@vercel/analytics": 1.5.0
  "@vercel/speed-insights": 1.2.0
  "@vis.gl/react-google-maps": 1.7.1
  "@vitejs/plugin-react": 5.1.1
  city-timezones: 1.3.2
  es-toolkit: 1.42.0
  eslint: 9.39.1
  eslint-config-next: 16.0.4
  eslint-config-prettier: 10.1.8
  eslint-plugin-import: 2.32.0
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-storybook: 10.0.8
  eslint-plugin-unicorn: 62.0.0
  gray-matter: 4.0.3
  jsdom: 27.2.0
  knip: 5.70.2
  lucide-react: 0.554.0
  moment-timezone: 0.6.0
  motion: 12.23.24
  next: 16.0.4
  next-mdx-remote: 5.0.0
  next-themes: 0.4.6
  openapi-fetch: 0.15.0
  openapi-react-query: 0.5.1
  openapi-typescript: 7.10.1
  postcss: 8.5.6
  prettier: 3.6.2
  prettier-plugin-tailwindcss: 0.7.1
  react: 19.2.0
  react-dom: 19.2.0
  react-icons: 5.5.0
  react-syntax-highlighter: 16.1.0
  storybook: 10.0.8
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  tsx: 4.20.6
  typescript: 5.9.3
  typescript-eslint: 8.48.0
  use-debounce: 10.0.6
  uuid: 13.0.0
  vitest: 4.0.14
  vitest-canvas-mock: 1.1.2
