ignoredBuiltDependencies:
  - canvas
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

# Deps allowed to run scripts during installation
# This is unsecure, so we limit it to only these packages that we trust
onlyBuiltDependencies:
  - "@heroui/shared-utils" # May be gone in heroui v3
  - msw # https://github.com/mswjs/msw/issues/1297

minimumReleaseAge: 20160
minimumReleaseAgeExclude:
  # Remove Feb 25th 2026
  - "next-mdx-remote@6.0.0"
