ignoredBuiltDependencies:
  - canvas
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

# Deps allowed to run scripts during installation
# This is unsecure, so we limit it to only these packages that we trust
onlyBuiltDependencies:
  - "@heroui/shared-utils" # May be gone in heroui v3
  - msw # https://github.com/mswjs/msw/issues/1297

minimumReleaseAge: 20160
minimumReleaseAgeExclude:
  # Remove Feb 15th 2026
  - "@babel/core@7.29.0"
  - "@babel/code-frame@7.29.0"
  - "@babel/types@7.29.0"
  - "@babel/generator@7.29.0"
  - "@babel/traverse@7.29.0"
  - "@babel/parser@7.29.0"
  # Remove Feb 14th 2026
  - "rollup@4.57.1"
  - "@rollup/rollup-linux-loong64-musl@4.57.1"
  - "@rollup/rollup-linux-ppc64-musl@4.57.1"
  - "@rollup/rollup-linux-loong64-gnu@4.57.1"
  - "@rollup/rollup-win32-x64-gnu@4.57.1"
  - "@rollup/rollup-linux-ppc64-gnu@4.57.1"
  - "@rollup/rollup-linux-riscv64-musl@4.57.1"
  - "@rollup/rollup-openbsd-x64@4.57.1"
  - "@rollup/rollup-freebsd-arm64@4.57.1"
  - "@rollup/rollup-freebsd-x64@4.57.1"
  - "@rollup/rollup-openharmony-arm64@4.57.1"
  - "@rollup/rollup-android-arm-eabi@4.57.1"
  - "@rollup/rollup-win32-arm64-msvc@4.57.1"
  - "@rollup/rollup-linux-arm-musleabihf@4.57.1"
  - "@rollup/rollup-linux-riscv64-gnu@4.57.1"
  - "@rollup/rollup-linux-s390x-gnu@4.57.1"
  - "@rollup/rollup-linux-arm64-musl@4.57.1"
  - "@rollup/rollup-win32-ia32-msvc@4.57.1"
  - "@rollup/rollup-linux-x64-gnu@4.57.1"
  - "@rollup/rollup-linux-x64-musl@4.57.1"
  - "@rollup/rollup-darwin-arm64@4.57.1"
  - "@rollup/rollup-android-arm64@4.57.1"
  - "@rollup/rollup-win32-x64-msvc@4.57.1"
  - "@rollup/rollup-linux-arm-gnueabihf@4.57.1"
  - "@rollup/rollup-darwin-x64@4.57.1"
  - "@rollup/rollup-linux-arm64-gnu@4.57.1"
  # Remove Feb 17th 2026
  - "@sentry/bundler-plugin-core@4.9.0"
  - "@sentry/webpack-plugin@4.9.0"
  - "@sentry/babel-plugin-component-annotate@4.9.0"
  - "icu-minify@4.8.2"
  - "next-intl-swc-plugin-extractor@4.8.2"
  - "use-intl@4.8.2"
  - "framer-motion@12.30.0"
  - "motion-dom@12.30.0"
  # Remove Feb 18th 2026
  - "next-mdx-remote@6.0.0"
